config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  namespace :gtd do
    resources :queues
  end
end

app/models/authentication_provider.rb
class AuthenticationProvider < ActiveRecord::Base
  has_many :social_accounts
  has_many :users
  has_many :user_authentications

  scope :get_provider_name, -> (provider_name) {where("name = ?",provider_name)}
end

app/models/concerns/omniauth_attributes_concern.rb
 module OmniauthAttributesConcern
      extend ActiveSupport::Concern
      module ClassMethods
        def facebook params
      (params['info']['email'] = "dummy#{SecureRandom.hex(10)}@dummy.com") if params['info']['email'].blank?
      attributes = {
        provider: params['provider'],
        uid: params['uid'],
                      email: params['info']['email'],
                      password: Devise.friendly_token
                  }
      create(attributes)
  end
        def twitter params
      (params['info']['email'] = "dummy#{SecureRandom.hex(10)}@dummy.com") if params['info']['email'].blank?
      attributes = {
        provider: params['provider'],
        uid: params['uid'],
                      email: params['info']['email'],
                      password: Devise.friendly_token
                  }
      create(attributes)
  end
        def gplus params
      (params['info']['email'] = "dummy#{SecureRandom.hex(10)}@dummy.com") if params['info']['email'].blank?
      attributes = {
        provider: params['provider'],
        uid: params['uid'],
                      email: params['info']['email'],
                      password: Devise.friendly_token
                  }
      create(attributes)
  end
        def linkedin params
      (params['info']['email'] = "dummy#{SecureRandom.hex(10)}@dummy.com") if params['info']['email'].blank?
      attributes = {
        provider: params['provider'],
        uid: params['uid'],
                      email: params['info']['email'],
                      password: Devise.friendly_token
                  }
      create(attributes)
  end
      end
 end
 

app/models/gtd.rb
module Gtd
  def self.table_name_prefix
    'gtd_'
  end
end

app/models/gtd/queue.rb
class Gtd::Queue < ActiveRecord::Base
  self.primary_key = 'id'
end

app/models/social_account.rb
class SocialAccount < ActiveRecord::Base
  belongs_to :user
  belongs_to :authentication_provider

  scope :get_provider_account , -> (user_id,auth_provider_id) { where("user_id = ? and authentication_provider_id = ? ",user_id,auth_provider_id) }
  scope :get_provider_name_account , -> (user_id,auth_provider_name) { where("user_id = ? and authentication_providers.name = ? ",user_id,auth_provider_name).joins(:authentication_provider) }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  self.primary_key = :id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include OmniauthAttributesConcern
    
  has_many :user_authentications

  devise :omniauthable, :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable

  def self.create_from_omniauth(params)
      self.send(params.provider,params)
  end
end

app/models/user_authentication.rb
class UserAuthentication < ActiveRecord::Base
  belongs_to :user
  belongs_to :authentication_provider
  
  serialize :params
  
  def self.create_from_omniauth(params, user, provider)
    token_expires_at = params['credentials']['expires_at'] ? Time.at(params['credentials']['expires_at']).to_datetime : nil
    create(
      user: user,
      authentication_provider: provider,
      uid: params['uid'],
      token: params['credentials']['token'],
      token_expires_at: token_expires_at,
      params: params,
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/concerns/omni_concern.rb
module OmniConcern
  extend ActiveSupport::Concern
  def create
    auth_params = request.env["omniauth.auth"]
    provider = AuthenticationProvider.get_provider_name(auth_params.try(:provider)).first
    authentication = provider.user_authentications.where(uid: auth_params.uid).first
    existing_user = User.where('email = ?', auth_params['info']['email']).try(:first)
    if user_signed_in?
      SocialAccount.get_provider_account(current_user.id,provider.id).first_or_create(user_id: current_user.id ,  authentication_provider_id: provider.id , token: auth_params.try(:[],"credentials").try(:[],"token") , secret: auth_params.try(:[],"credentials").try(:[],"secret"))
      redirect_to new_user_registration_url
    elsif authentication
      create_authentication_and_sign_in(auth_params, existing_user, provider)
    else
      create_user_and_authentication_and_sign_in(auth_params, provider)
    end
  end
  def sign_in_with_existing_authentication(authentication)
    sign_in_and_redirect(:user, authentication.user)
  end
  def create_authentication_and_sign_in(auth_params, user, provider)
    UserAuthentication.create_from_omniauth(auth_params, user, provider)
    sign_in_and_redirect(:user, user) 
  end
  def create_user_and_authentication_and_sign_in(auth_params, provider)
    user = User.create_from_omniauth(auth_params)
    if user.valid?
      create_authentication_and_sign_in(auth_params, user, provider)
    else
      flash[:error] = user.errors.full_messages.first
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/gtd/queues_controller.rb
class Gtd::QueuesController < ApplicationController
  before_action :set_gtd_queue, only: [:show, :edit, :update, :destroy]

  # GET /gtd/queues
  # GET /gtd/queues.json
  def index
    @gtd_queues = Gtd::Queue.where(user: current_user.id)
  end

  # GET /gtd/queues/1
  # GET /gtd/queues/1.json
  def show
  end

  # GET /gtd/queues/new
  def new
    @gtd_queue = Gtd::Queue.new
  end

  # GET /gtd/queues/1/edit
  def edit
  end

  # POST /gtd/queues
  # POST /gtd/queues.json
  def create
    @gtd_queue = Gtd::Queue.new(gtd_queue_params)
    @gtd_queue.user = current_user.id

    respond_to do |format|
      if @gtd_queue.save
        format.html { redirect_to @gtd_queue, notice: 'Queue was successfully created.' }
        format.json { render :show, status: :created, location: @gtd_queue }
      else
        format.html { render :new }
        format.json { render json: @gtd_queue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gtd/queues/1
  # PATCH/PUT /gtd/queues/1.json
  def update
    respond_to do |format|
      if @gtd_queue.update(gtd_queue_params)
        format.html { redirect_to @gtd_queue, notice: 'Queue was successfully updated.' }
        format.json { render :show, status: :ok, location: @gtd_queue }
      else
        format.html { render :edit }
        format.json { render json: @gtd_queue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gtd/queues/1
  # DELETE /gtd/queues/1.json
  def destroy
    @gtd_queue.destroy
    respond_to do |format|
      format.html { redirect_to gtd_queues_url, notice: 'Queue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gtd_queue
      @gtd_queue = Gtd::Queue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gtd_queue_params
      params.require(:gtd_queue).permit(:id, :name, :description)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include OmniConcern
  %w[facebook twitter gplus linkedin].each do |meth|
    define_method(meth) do
      create
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gtd/queues_helper.rb
module Gtd::QueuesHelper
end

app/views/dashboard/index.html.erb
<h1>Hello</h1>

<%= link_to 'Queues', 'gtd/queues' %>
  

app/views/gtd/queues/_form.html.erb
<%= form_for(@gtd_queue) do |f| %>
  ID: <%= @gtd_queue.id %><br/>
  Name: <%= f.text_field :name %><br/>
  Description: <%= f.text_area :description %><br/>
  <% if @gtd_queue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gtd_queue.errors.count, "error") %> prohibited this gtd_queue from being saved:</h2>

      <ul>
      <% @gtd_queue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gtd/queues/edit.html.erb
<h1>Editing Gtd Queue</h1>

<%= render 'form' %>

<%= link_to 'Show', @gtd_queue %> |
<%= link_to 'Back', gtd_queues_path %>

app/views/gtd/queues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gtd Queues</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gtd_queues.each do |gtd_queue| %>
      <tr>
        <td><%= link_to gtd_queue.name, gtd_queue %></td>
        <td><%= link_to 'Edit', edit_gtd_queue_path(gtd_queue) %></td>
        <td><%= link_to 'Destroy', gtd_queue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Queue', new_gtd_queue_path %>

app/views/gtd/queues/new.html.erb
<h1>New Gtd Queue</h1>

<%= render 'form' %>

<%= link_to 'Back', gtd_queues_path %>

app/views/gtd/queues/show.html.erb
<p id="notice"><%= notice %></p>

ID: <%= @gtd_queue.id %><br/>
Name: <%= @gtd_queue.name %><br/>
Description: <%= @gtd_queue.description %><br/>
<%= link_to 'Edit', edit_gtd_queue_path(@gtd_queue) %> |
<%= link_to 'Back', gtd_queues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelenOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
  <div>
    Signed in as <%= current_user.email %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </div>
  <% else %>
  <div>
    <%= link_to('Login', new_user_session_path) %>
  </div>
  <% end %>
  <% flash.each do |key, value| %>
  <div>
    <ul>
      <li>
	<%= value %>
      </li>
    </ul>
  </div>
  <% end %>
  <%= yield %>
<div>Try downloading the <a href="https://github.com/quarkbuddha/helen_in_pocket/releases/download/latest/helen.apk">Android app</a></div>
</body>
</html>